---
- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart network manager
  service: name=network-manager state=restarted

- name: reload ssh
  service:
    name: ssh
    state: restarted